markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Zach Holman
url: http://zachholman.com
description: A fantastic blog that is fantastic.
twitter: holman
