markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Han Loong
url: http://hanloongliauw.com
description: A fantastic blog that coud be fantastic.
twitter: hanloongliauw
github: hanloong
gravatar_url: http://www.gravatar.com/avatar/2abe46b3ec11871a750756561dfca874.png
