markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Alejandro Garc√≠a F. (El Viejo)
url: http://elviejo79.github.io
description: Still Learning to develop software.
github: elviejo79
gravatar_url: http://www.gravatar.com/avatar/d6eaf9adc428a1358c963cff1c15b77c